SoftUniBootcamPrep/todo_notes/app/urls.py
from django.urls import path

from app.views import AddNoteView, EditNoteView, DeleteNoteView, DetailsView, home, profile

"""
    • http://localhost:8000/ - home page
    • http://localhost:8000/add - add note page
    • http://localhost:8000/edit/:id - edit note page
    • http://localhost:8000/delete/:id - delete note page
    • http://localhost:8000/details/:id - note details page
    • http://localhost:8000/profile - profile page
"""

urlpatterns = [

    path('', home, name='home page'),
    path('add/', AddNoteView.as_view(), name='add note page'),
    path('edit/<int:pk>/', EditNoteView.as_view(), name='edit note page'),
    path('delete/<int:pk>/', DeleteNoteView.as_view(), name='delete note page'),
    path('details/<int:pk>/', DetailsView.as_view(), name='note details page'),
    path('profile/', profile, name='profile page'),

]

SoftUniBootcamPrep/todo_notes/todo_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

SoftUniBootcamPrep/todo_notes/app/models.py
from django.db import models

"""
    • Profile
        ◦ first_name - Character field with max length of 20 characters
        ◦ last_name - Character field with max length of 20 characters
        ◦ age - Integer field
        ◦ image_url - URL field
    • Note
        ◦ title - Character field with max length of 30 characters
        ◦ image_url - URL field
        ◦ content - Text field
"""


class Profile(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField()
    image_url = models.URLField()

    def __str__(self):
        return f"{self.first_name}'s profile"


class Note(models.Model):
    title = models.CharField(max_length=30)
    image_url = models.URLField()
    content = models.TextField()
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, default=Profile)

    def __str__(self):
        return f'{self.title} note'

SoftUniBootcamPrep/todo_notes/app/forms.py
from django import forms

from app.models import Note


class DeleteRecipeForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for (_, field) in self.fields.items():
            field.widget.attrs['disabled'] = True
            field.widget.attrs['readonly'] = True

SoftUniBootcamPrep/todo_notes/app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.edit import ModelFormMixin

from app.forms import DeleteRecipeForm
from app.models import Note, Profile


def home(request):
    profile = Profile.objects.exists()
    if profile:
        return HomeView.as_view()(request)
    return AddProfile.as_view()(request)


class HomeView(ListView):
    template_name = 'home-with-profile.html'
    model = Note


class AddProfile(CreateView):
    model = Profile
    template_name = 'home-no-profile.html'
    fields = '__all__'
    success_url = '/'


class AddNoteView(CreateView):
    model = Note
    template_name = 'note-create.html'
    fields = '__all__'
    success_url = '/'


class EditNoteView(UpdateView):
    model = Note
    template_name = 'note-edit.html'
    fields = '__all__'
    success_url = '/'


class DeleteNoteView(DeleteView, ModelFormMixin, DeleteRecipeForm):
    model = Note
    template_name = 'note-delete.html'
    success_url = '/'
    # fields = '__all__'
    form_class = DeleteRecipeForm


class DetailsView(DetailView):
    template_name = 'note-details.html'
    model = Note


def profile(request):
    profile_to_show = Profile.objects.first()
    notes = profile_to_show.note_set.count()
    context = {
        'profile': profile_to_show,
        'notes': notes
    }
    if request.method == 'POST':
        profile_to_show.delete()
        return redirect('/')
    return render(request, 'profile.html', context)

SoftUniBootcamPrep/todo_notes/templates/home-no-profile.html
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" width="32" height="32" /></li>

                    <li><a href="/">Notes</a></li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Enter Your Data</h1>
            <!--end headings-->

            <!--profile data form-->
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0" />#}
                    <label for="firstName">First Name</label>
                    {{ form.first_name }}
{#                    <input type="text" name="first_name" maxlength="15" required="" id="id_first_name" />#}

                    <label for="lastName">Last Name</label>
{#                    <input type="text" name="last_name" maxlength="15" required="" id="id_last_name" />#}
                    {{ form.last_name }}

                    <label for="age">Age</label>
{#                    <input type="number" name="age" required="" id="id_age" />#}
                    {{ form.age }}

                    <label for="profilePhoto">Link to Profile Image</label>
{#                    <input type="url" name="profile_image" required="" id="id_image" />#}
                    {{ form.image_url }}

                    <input type="submit" value="SUBMIT" />
                </form>
            </div>
            <!--end profile data form-->
        </div>

        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

SoftUniBootcamPrep/todo_notes/templates/home-with-profile.html
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href={% url 'home page' %}>Notes</a></li>
                    <li class="right">
                        <a href={% url 'add note page' %}>Add Note</a>
                        <a href="{% url 'profile page'%}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <h1>My Notes</h1>

        {% if not object_list %}
        <h2>There are no notes.</h2>
        <!--notes container-->
        {% else %}
        {% for task in object_list %}
        <div class="note-container">
            <h2>{{ task.title}} <img src={{ task.image_url }} /></h2>

            <div class="right">
                <a class="button details" href="{% url 'note details page' task.id %}">Details</a>
                <a class="button edit" href="{% url 'edit note page' task.id %}">Edit</a>
                <a class="button delete" href="{% url 'delete note page' task.id %}">Delete</a>
            </div>
        </div>
        {% endfor %}
        {% endif %}

        <!--end notes container-->

        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

SoftUniBootcamPrep/todo_notes/templates/note-create.html
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <title>Notes</title>
</head>

<body>
<!--navigation bar-->
<header>
    <nav>
        <ul>
            <li class="img"><img src="/static/images/note.png"/></li>
            <li><a href="/">Notes</a></li>
            <li class="right"><a href="/profile">Profile</a></li>
        </ul>
    </nav>
</header>
<!--end navigation bar-->

<div class="body">
    <!--headings-->
    <h1>Add Note</h1>
    <!--headings-->

    <!--note data form-->
    <div class="form">
        <form method="POST">
            {% csrf_token %}
            {#                    <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw" />#}
            <label for="name">Title</label>
            {#                    <input type="text" name="title" maxlength="50" required="" id="id_title" />#}
            {{ form.title }}

            <label for="content">Content</label>
            {#                    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
            {{ form.content }}

            <label for="image_url">Link to Image</label>
            {#                    <input type="url" name="image_url" maxlength="200" required="" id="id_image_url" />#}
            {{ form.image_url }}
            <div hidden="hidden">
            {{ form.owner }}
            </div>
            <input type="submit" value="Publish"/>
        </form>
    </div>
    <!--end note data form-->
</div>

<!--footer-->
<footer>
    <div>Python Web Basics Exam @SoftUni</div>
</footer>
<!--end footer-->
</body>
</html>

SoftUniBootcamPrep/todo_notes/templates/note-delete.html
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <title>Notes</title>
</head>

<body>
<!--navigation bar-->
<header>
    <nav>
        <ul>
            <li class="img"><img src="/static/images/note.png"/></li>
            <li><a href="/">Notes</a></li>
            <li class="right">
                <a href="/add">Add Note</a>
                <a href="/profile">Profile</a>
            </li>
        </ul>
    </nav>
</header>
<!--navigation bar-->

<div class="body">
    <!--headings-->
    <h1>Delete Note</h1>
    <!--headings-->

    <!--note delete data form-->
    <div class="form">
        <form method="POST">
            {% csrf_token %}
            {#                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />#}
            <label for="name">Title</label>
            {#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" disabled="" required="" id="id_title" />#}
            {{ form.title }}
            <label for="content">Content</label>
            {#                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">#}
            {#Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.#}
            {##}
            {#                    </textarea>#}
            {{ form.content }}

            <label for="image_url">Link to Image</label>
            {#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" disabled="" required="" id="id_image_url" />#}
            {{ form.image_url }}
            <div hidden="hidden">
                {{ form.owner }}
            </div>
            <input type="submit" value="Delete"/>
        </form>
    </div>
    <!--end note delete data form-->
</div>

<!--footer-->
<footer>
    <div>Python Web Basics Exam @SoftUni</div>
</footer>
<!--end footer-->
</body>
</html>

SoftUniBootcamPrep/todo_notes/templates/note-details.html
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="/">Notes</a></li>
                    <li class="right">
                        <a href="/add">Add Note</a>
                        <a href="/profile">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Note Details</h1>
            <!--headings-->

            <!--details note box-->
            <div class="note-details-container">
                <h2>{{ object.title}}</h2>
                <img class="detail-img" src="{{ object.image_url }}" />
                <div>
                    <p>Content</p>
                </div>
                <p>
                    {{ object.content}}
                </p>
                <div class="right">
                    <a class="button edit" href="{% url 'edit note page' object.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete note page' object.id %}">Delete</a>
                </div>
            </div>
            <!--end details note box-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

SoftUniBootcamPrep/todo_notes/templates/note-edit.html
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="/static/images/note.png" /></li>
                    <li><a href="/">Notes</a></li>
                    <li class="right">
                        <a href="/add">Add Note</a>
                        <a href="/profile">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Edit Note</h1>
            <!--headings-->

            <!--note edit data form-->
            <div class="form">
                <form method="POST">
            {% csrf_token %}
            {#                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />#}
            <label for="name">Title</label>
            {#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" disabled="" required="" id="id_title" />#}
            {{ form.title }}
            <label for="content">Content</label>
            {#                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">#}
            {#Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.#}
            {##}
            {#                    </textarea>#}
            {{ form.content }}

            <label for="image_url">Link to Image</label>
            {#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" disabled="" required="" id="id_image_url" />#}
            {{ form.image_url }}
            <div hidden="hidden">
                {{ form.owner }}
            </div>
            <input type="submit" value="Edit"/>
        </form>
            </div>
            <!--end note edit data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

SoftUniBootcamPrep/todo_notes/templates/profile.html
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <title>Notes</title>
</head>

<body>
<!--navigation bar-->
<header>
    <nav>
        <ul>
            <li class="img"><img src="/static/images/note.png"/></li>
            <li><a href="/">Notes</a></li>
            <li class="right">
                <a href="/add">Add Note</a>
                <a href="/profile">Profile</a>
            </li>
        </ul>
    </nav>
</header>
<!--end navigation bar-->

<div class="body">
    <!--headings-->
    <h1>Your Profile</h1>
    <!--end headings-->

    <!--profile details container TODO-->
    <div class="note-container">
        <h2>
            {{ profile.first_name }} {{ profile.last_name }}
            <img src={{ profile.image_url }}/>
        </h2>
        <p>Age: {{ profile.age }}</p>
        <div>
            <p>All notes: {{ notes }}</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="right">
                <input style="background: transparent" type="submit" value="Delete"/>
            </div>
        </form>
    </div>
    <!--end profile details container-->
</div>

<!--footer-->
<footer>
    <div>Python Web Basics Exam @SoftUni</div>
</footer>
<!--end footer-->
</body>
</html>